// Package setup renders, installs, validates, and updates the systemd
// --user units and tmux.conf snippet go-tmux-saver needs to run itself
// (periodic snapshots, a freshness watchdog, restore-on-start, and the
// M-s/M-r tmux key bindings), plus a default config.json. It is the engine
// behind the `setup` CLI subcommand in internal/cli/setup.go.
package setup

import (
	"bytes"
	"embed"
	"encoding/json"
	"fmt"
	"os"
	"text/template"

	"github.com/mithro/go-tmux-saver/internal/config"
)

//go:embed templates/*.tmpl
var templatesFS embed.FS

// Header is prepended (with Params.Version substituted in) to every
// rendered file except config.json, which must stay pure JSON.
const Header = "# managed by go-tmux-saver %s — edit config.json, not this file; run 'go-tmux-saver setup update'\n"

// Rel* are the ConfigHome-relative paths of the files Render produces, in
// the same order Render returns them.
const (
	RelService      = "systemd/user/go-tmux-saver.service"
	RelTimer        = "systemd/user/go-tmux-saver.timer"
	RelWatchService = "systemd/user/go-tmux-saver-watch.service"
	RelWatchTimer   = "systemd/user/go-tmux-saver-watch.timer"
	RelAlertService = "systemd/user/go-tmux-saver-alert@.service"
	RelTmuxDropin   = "systemd/user/tmux-server.service.d/50-go-tmux-saver.conf"
	RelTmuxConf     = "go-tmux-saver/tmux.conf"
	RelConfigJSON   = "go-tmux-saver/config.json"
)

// unitMode and configMode are the modes Render assigns; Validate and
// Install/Update rely on these being consistent with what Render produces.
const (
	unitMode   os.FileMode = 0o644
	configMode os.FileMode = 0o600
)

// Params are the values substituted into the managed-file templates.
type Params struct {
	Version         string
	Binary          string
	Socket          string
	SeedSession     string
	SeedWindow      string
	IntervalMinutes int
	MailTo          string
}

// Managed is one file Render produces: a path relative to Env.ConfigHome,
// its rendered content, and the mode it must be written/checked with.
type Managed struct {
	Rel     string
	Content []byte
	Mode    os.FileMode
}

// templateData is what the .tmpl files see: Params' fields plus the
// pre-formatted Header string (ruling R5: Header = fmt.Sprintf(Header,
// Version)).
type templateData struct {
	Params
	Header string
}

// tmplSpec describes one embedded template: its file name under
// templates/, the ConfigHome-relative path it renders to, and its mode.
type tmplSpec struct {
	file string
	rel  string
	mode os.FileMode
}

// specs lists the templated files in Render's deterministic output order.
// config.json is handled separately (it is not templated — see Render).
var specs = []tmplSpec{
	{"go-tmux-saver.service.tmpl", RelService, unitMode},
	{"go-tmux-saver.timer.tmpl", RelTimer, unitMode},
	{"go-tmux-saver-watch.service.tmpl", RelWatchService, unitMode},
	{"go-tmux-saver-watch.timer.tmpl", RelWatchTimer, unitMode},
	{"go-tmux-saver-alert@.service.tmpl", RelAlertService, unitMode},
	{"tmux-server-dropin.conf.tmpl", RelTmuxDropin, unitMode},
	{"tmux.conf.tmpl", RelTmuxConf, unitMode},
}

// Render produces the full set of managed files for p, in a deterministic
// order (specs, then config.json last). Every file except config.json
// starts with the managed header; config.json is plain JSON of
// config.Default() (mode 0600) so it stays user-editable and machine
// parseable, and is never regenerated by Update once it exists.
func Render(p Params) ([]Managed, error) {
	tmpl, err := template.ParseFS(templatesFS, "templates/*.tmpl")
	if err != nil {
		return nil, fmt.Errorf("setup: parse templates: %w", err)
	}

	data := templateData{Params: p, Header: fmt.Sprintf(Header, p.Version)}

	out := make([]Managed, 0, len(specs)+1)
	for _, spec := range specs {
		var buf bytes.Buffer
		if err := tmpl.ExecuteTemplate(&buf, spec.file, data); err != nil {
			return nil, fmt.Errorf("setup: render %s: %w", spec.file, err)
		}
		out = append(out, Managed{Rel: spec.rel, Content: buf.Bytes(), Mode: spec.mode})
	}

	cfgJSON, err := json.MarshalIndent(config.Default(), "", "  ")
	if err != nil {
		return nil, fmt.Errorf("setup: marshal default config: %w", err)
	}
	cfgJSON = append(cfgJSON, '\n')
	out = append(out, Managed{Rel: RelConfigJSON, Content: cfgJSON, Mode: configMode})

	return out, nil
}
